//PRODUCTS
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_LIST_PRODUCTS = 'SET_LIST_PRODUCTS';
export const SET_LIST_CATEGORIES_PRODUCTS = 'SET_LIST_CATEGORIES_PRODUCTS';
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR';

//USER
export const SET_USER = 'SET_USER';
export const SET_LIST_USERS = 'SET_LIST_USERS';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_ERROR = 'SET_USER_ERROR';

//ORDER
export const SET_ORDER = 'SET_ORDER';
export const SET_LIST_ORDERS = 'SET_LIST_ORDERS';
export const SET_ORDER_LOADING = 'SET_ORDER_LOADING';
export const SET_ORDER_ERROR = 'SET_ORDER_ERROR';

//WILAYAH
export const SET_LIST_PROVINSI = 'SET_LIST_PROVINSI';
export const SET_LIST_KABUPATEN = 'SET_LIST_KABUPATEN';
export const SET_LIST_KECAMATAN = 'SET_LIST_KECAMATAN';
export const SET_LIST_KELURAHAN = 'SET_LIST_KELURAHAN';
export const SET_LIST_WILAYAH_LOADING = 'SET_LIST_WILAYAH_LOADING';
export const SET_LIST_WILAYAH_ERROR = 'SET_LIST_WILAYAH_ERROR';
